import org.junit.Test;
import static org.junit.Assert.*;

public class FriendScoreTest {
	
	@Test(timeout=2000)
	public void test0() {
		String[] friends = new String[] {"NNN",
 "NNN",
 "NNN"};
		assertEquals(0, new FriendScore().highestScore(friends));
	}
	
	@Test(timeout=2000)
	public void test1() {
		String[] friends = new String[] {"NYY",
 "YNY",
 "YYN"};
		assertEquals(2, new FriendScore().highestScore(friends));
	}
	
	@Test(timeout=2000)
	public void test2() {
		String[] friends = new String[] {"NYNNN",
 "YNYNN", 
 "NYNYN", 
 "NNYNY", 
 "NNNYN"};
		assertEquals(4, new FriendScore().highestScore(friends));
	}
	
	@Test(timeout=2000)
	public void test3() {
		String[] friends = new String[] {"NNNNYNNNNN",
 "NNNNYNYYNN",
 "NNNYYYNNNN",
 "NNYNNNNNNN",
 "YYYNNNNNNY",
 "NNYNNNNNYN",
 "NYNNNNNYNN",
 "NYNNNNYNNN",
 "NNNNNYNNNN",
 "NNNNYNNNNN"};
		assertEquals(8, new FriendScore().highestScore(friends));
	}
	
	@Test(timeout=2000000000)
	public void test4() {
		String[] friends = new String[] {"NNNNNNNNYNNNNYNNNNNNNNYNNNNNNNNNY", "NNNNNYNNYNNNNNNNYNNNYNNYNNNNNNNNN", "NNNNNNNYNNNNNYNYYNYNNYNNNNYNYYYNN", "NNNNNNNNYNNNNNNNNNNNNYNYNNNNYNNNN", "NNNNNNNNYNNYYNNNNNNNNNNNYNN    NNNNNN", "NYNNNNNNNNYNNNNYNNNYYNNNNNNNYNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNYNYNNNYNY", "NNYNNNNNNNNNYNNYNYNNNNYYNNNNNNNNN", "YYNYYNNNNNNNNNNNYNYNNNNNNYNNYNNNY", "NNNNNNNNNNNYNNNNYNN    NNNYNNNNNNNNNN", "NNNNNYNNNNNYNYNNNNNNYNNNNYNNYNNNN", "NNNNYNNNNYYNYYYNNNNNYNNNNYNNNNNYY", "NNNNYNNYNNNYNNNNNNNNNNNNNNNNNNNNN", "YNYNNNNNNNYYNNNNNNNNNNNNNNYNNYNNY", "NNNNNNNNNNN    YNNNNNNNNYNNNNNNYYYNYN", "NNYNNYNYNNNNNNNNNNNYNNNNNYNNNNNNN", "NYYNNNNNYYNNNNNNNNNNNNNNNNNYNYNNN", "NNNNNNNYNNNNNNNNNNNNNYNYYNNNNNNNN", "NNYNNNNNYNNNNNNNNNNNNNNNNNNNYYYYN", "NNN    NNYNNNNNNNNNYNNNNYNNNNYNNNYYNY", "NYNNNYYNNNYYNNYNNNNYNNNNNNYNYNNNY", "NNYYNNNNNNNNNNNNNYNNNNNNNYNNNYNNN", "YNNNNNNYNYNNNNNNNNNNNNNYNNYNNNYNN", "NYNYNNNYNNNNNNNNNYNNNNYNYNYNNNNN    Y", "NNNNYNYNNNNNNNNNNYNNNNNYNNYNNNNNN", "NNNNNNNNYNYYNNNYNNNYNYNNNNNNNNNNN", "NNYNNNYNNNNNNYNNNNNNYNYYYNNYNNYNY", "NNNNNNNNNNNNNNYNYNNNNNNNNNYNNNNNY", "NNYYNYNNYNYNNNYNNNYNYNNN    NNNNNYNNN", "NNYNNNNNNNNNNYYNYNYYNYNNNNNNYNNNN", "NNYNNNYNNNNNNNNNNNYYNNYNNNYNNNNNN", "NNNNNNNNNNNYNNYNNNYNNNNNNNNNNNNNN", "YNNNNNYNYNNYNYNNNNNYYNNYNNYYNNNNN"};
		assertEquals(31, new FriendScore().highestScore(friends));
	}
}
